In [10]:
import numpy as np

F = np.array([[2.0, 3.0],
              [0.0, 1.0]])
x = np.array([[10],
              [20]])



In [11]:
F

array([[2., 3.],
       [0., 1.]])

In [12]:
F.shape

(2, 2)

In [13]:
x

array([[10],
       [20]])

In [6]:
np.matmul(F,x)

array([80., 20.])

In [14]:
F@x

array([[80.],
       [20.]])

In [2]:
[10,20] @ [30,40]

TypeError: unsupported operand type(s) for @: 'list' and 'list'

In [2]:
import numpy as np
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
A = np.array([[10,10],
              [10,10]])

In [6]:
A*0.9

array([[9., 9.],
       [9., 9.]])

In [ ]:
A * A

array([[100, 100],
       [100, 100]])